### ISSUE TITLE
ENOENT: no such file or directory error on Windows

### ISSUE THREAD

**Issue by MaxRomanik** [ShieldMyFiles/duly-noted#10]
Running duly-noted on a Win10 VM yielded the following error:

> Error: ENOENT: no such file or directory

Error is likely Win. specific.

**Comment by christophersw** [comment]
I think this is due to a missing `./` in the definition of the `parseLoc`... See this thread for more details - http://stackoverflow.com/questions/9047094/node-js-error-enoent.

I am working on a fix - should have something push for you to try shortly.

**Comment by christophersw** [comment]
My previous efforts did not fix this... I have replicated the error on another Windows box, so we know at least this is a real bug...

**Comment by christophersw** [comment]
This should be fixed in v 2.7.4 which I just published.
